apiVersion: v1
kind: Pod
metadata:
  labels:
    app: config-demo
  name: config-demo
spec:
  containers:
    - image: gcr.io/mytest1-305713/config-demo-img
      name: config-demo
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      env:      
        - name: SPRING_PROFILE
          value: dev
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: dev-config.json
  restartPolicy: Never 

---
apiVersion: v1
kind: Service
metadata:
  name: config-service-name
  labels:
    app: callme-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  selector:
    app: config-demo
          
                
